apiVersion: v1
kind: Service
metadata:
  name: scotchbase-service
  labels:
    app: scotchbase
spec:
  type: NodePort
  selector:
    app: scotchbase
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
